<?php
// show the country and country selection in the form
// DO NOT change the option value text - it matches the flag image names!!

echo "<tr><td><p>Country (flag):</p></td>";
echo "<td style='text-align:right;'>";

echo "
<select name='country'>
<option value='blank'>Please Choose</option>
<option value='canada'>Canada</option>
<option value='uk'>UK</option>
<option value='usa'>USA</option>
<option value='afghanistan'>Afghanistan</option>
<option value='albania'>Albania</option>
<option value='algeria'>Algeria</option>
<option value='andorra'>Andorra</option>
<option value='angola'>Angola</option>
<option value='antigua_barbuda'>Antigua Barbuda</option>
<option value='argentina'>Argentina</option>
<option value='armenia'>Armenia</option>
<option value='australia'>Australia</option>
<option value='austria'>Austria</option>
<option value='azerbaijan'>Azerbaijan</option>
<option value='bahamas'>Bahamas</option>
<option value='bahrain'>Bahrain</option>
<option value='bangladesh'>Bangladesh</option>
<option value='barbados'>Barbados</option>
<option value='belarus'>Belarus</option>
<option value='belgium'>Belgium</option>
<option value='belize'>Belize</option>
<option value='benin'>Benin</option>
<option value='bhutan'>Bhutan</option>
<option value='bolivia'>Bolivia</option>
<option value='bosnia_herzegovina'>Bosnia Herzegovina</option>
<option value='botswana'>Botswana</option>
<option value='brazil'>Brazil</option>
<option value='brunei'>Brunei</option>
<option value='bulgaria'>Bulgaria</option>
<option value='burkina_faso'>Burkina Faso</option>
<option value='burma'>Burma</option>
<option value='burundi'>Burundi</option>
<option value='cambodia'>Cambodia</option>
<option value='cameroon'>Cameroon</option>
<option value='central_african_rep'>Central African Rep</option>
<option value='chad'>Chad</option>
<option value='chile'>Chile</option>
<option value='china'>China</option>
<option value='columbia'>Columbia</option>
<option value='comoros'>Comoros</option>
<option value='congo'>Congo</option>
<option value='costa_rica'>Costa Rica</option>
<option value='croatia'>Croatia</option>
<option value='cuba'>Cuba</option>
<option value='cyprus'>Cyprus</option>
<option value='czech_republic'>Czech Republic</option>
<option value='dem_rep_congo'>DR Congo</option>
<option value='denmark'>Denmark</option>
<option value='djiboutil'>Djiboutil</option>
<option value='dominica'>Dominica</option>
<option value='dominican_rep'>Dominican Rep</option>
<option value='ecuador'>Ecuador</option>
<option value='egypt'>Egypt</option>
<option value='el_salvador'>El Salvador</option>
<option value='eq_guinea'>Eq Guinea</option>
<option value='eritrea'>Eritrea</option>
<option value='estonia'>Estonia</option>
<option value='ethiopia'>Ethiopia</option>
<option value='fiji'>Fiji</option>
<option value='finland'>Finland</option>
<option value='france'>France</option>
<option value='gabon'>Gabon</option>
<option value='gambia'>Gambia</option>
<option value='georgia'>Georgia</option>
<option value='germany'>Germany</option>
<option value='ghana'>Ghana</option>
<option value='greece'>Greece</option>
<option value='grenada'>Grenada</option>
<option value='grenadines'>Grenadines</option>
<option value='guatemala'>Guatemala</option>
<option value='guinea_bissau'>Guinea Bissau</option>
<option value='guineal'>Guinea</option>
<option value='guyana'>Guyana</option>
<option value='haiti'>Haiti</option>
<option value='honduras'>Honduras</option>
<option value='hong_kong'>Hong Kong</option>
<option value='hungary'>Hungary</option>
<option value='iceland'>Iceland</option>
<option value='india'>India</option>
<option value='indonesia'>Indonesia</option>
<option value='iran'>Iran</option>
<option value='iraq'>Iraq</option>
<option value='ireland'>Ireland</option>
<option value='israel'>Israel</option>
<option value='italy'>Italy</option>
<option value='ivory_coast'>Ivory Coast</option>
<option value='jamaica'>Jamaica</option>
<option value='japan'>Japan</option>
<option value='jordan'>Jordan</option>
<option value='kazakhstan'>Kazakhstan</option>
<option value='kenya'>Kenya</option>
<option value='kiribati'>Kiribati</option>
<option value='kuwait'>Kuwait</option>
<option value='kyrgyzstan'>Kyrgyzstan</option>
<option value='laos'>Laos</option>
<option value='latvia'>Latvia</option>
<option value='lebanon'>Lebanon</option>
<option value='liberia'>Liberia</option>
<option value='libya'>Libya</option>
<option value='liechtenstein'>Liechtenstein</option>
<option value='lithuania'>Lithuania</option>
<option value='luxembourg'>Luxembourg</option>
<option value='macedonia'>Macedonia</option>
<option value='macau'>Macau</option>
<option value='madagascar'>Madagascar</option>
<option value='malawi'>Malawi</option>
<option value='malaysia'>Malaysia</option>
<option value='maldives'>Maldives</option>
<option value='mali'>Mali</option>
<option value='malta'>Malta</option>
<option value='mauritania'>Mauritania</option>
<option value='mauritius'>Mauritius</option>
<option value='mexico'>Mexico</option>
<option value='micronesia'>Micronesia</option>
<option value='moldova'>Moldova</option>
<option value='monaco'>Monaco</option>
<option value='mongolia'>Mongolia</option>
<option value='morocco'>Morocco</option>
<option value='mozambique'>Mozambique</option>
<option value='namibia'>Namibia</option>
<option value='nauru'>Nauru</option>
<option value='nepal'>Nepal</option>
<option value='neth_antilles'>Neth Antilles</option>
<option value='netherlands'>Netherlands</option>
<option value='new_zealand'>New Zealand</option>
<option value='nicaragua'>Nicaragua</option>
<option value='niger'>Niger</option>
<option value='nigeria'>Nigeria</option>
<option value='north_korea'>North Korea</option>
<option value='norway'>Norway</option>
<option value='oman'>Oman</option>
<option value='pakistan'>Pakistan</option>
<option value='panama'>Panama</option>
<option value='papua_new_guinea'>Papua New Guinea</option>
<option value='paraguay'>Paraguay</option>
<option value='peru'>Peru</option>
<option value='philippines'>Philippines</option>
<option value='poland'>Poland</option>
<option value='portugal'>Portugal</option>
<option value='puerto_rico'>Puerto Rico</option>
<option value='qatar'>Qatar</option>
<option value='rawanda'>Rawanda</option>
<option value='romania'>Romania</option>
<option value='russia'>Russia</option>
<option value='sao_tome'>Sao Tome</option>
<option value='saudi_arabia'>Saudi Arabia</option>
<option value='scotland'>Scotland</option>
<option value='senegal'>Senegal</option>
<option value='serbia'>Serbia</option>
<option value='seychelles'>Seychelles</option>
<option value='sierra_leone'>Sierra Leone</option>
<option value='singapore'>Singapore</option>
<option value='slovakia'>Slovakia</option>
<option value='slovenia'>Slovenia</option>
<option value='solomon_islands'>Solomon Islands</option>
<option value='somalia'>Somalia</option>
<option value='south_korea'>South Korea</option>
<option value='south_africa'>South Africa</option>
<option value='spain'>Spain</option> 
<option value='sri_lanka'>Sri Lanka</option>
<option value='st_kitts_and_nevis'>St Kitts and Nevis</option>
<option value='st_lucia'>St Lucia</option>
<option value='sudan'>Sudan</option>
<option value='suriname'>Suriname</option>
<option value='sweden'>Sweden</option>
<option value='switzerland'>Switzerland</option>
<option value='syria'>Syria</option>
<option value='taiwan'>Taiwan</option>
<option value='tajikistan'>Tajikistan</option>
<option value='tanzania'>Tanzania</option>
<option value='thailand'>Thailand</option>
<option value='togo'>Togo</option>
<option value='tonga'>Tonga</option>
<option value='trinidad_and_tobago'>Trinidad and Tobago</option>
<option value='tunisia'>Tunisia</option>
<option value='turkey'>Turkey</option>
<option value='turkmenistan'>Turkmenistan</option>
<option value='tuvala'>Tuvala</option>
<option value='uae'>UAE</option>
<option value='uganda'>Uganda</option>
<option value='ukraine'>Ukraine</option>
<option value='uruguay'>Uruguay</option>
<option value='uzbekistan'>Uzbekistan</option>
<option value='vanuatu'>Vanuatu</option>
<option value='venezuela'>Venezuela</option>
<option value='vietnam'>Vietnam</option>
<option value='western_samoa'>Western Samoa</option>
<option value='wales'>Wales</option>
<option value='yemen'>Yemen</option>
<option value='yugoslavia'>Yugoslavia</option>
<option value='zaire'>Zaire</option>
<option value='zambia'>Zambia</option>
<option value='zimbabwe'>Zimbabwe</option>
</select>";
echo "</td></tr>";
?>